config/routes.rb
Namratafolio::Application.routes.draw do

  root :to => 'projects#namrataproject'

  resources :projects
  match 'about', to: 'static_pages#about'
  match 'blog', to: 'static_pages#blog' 
  match 'contact', to: 'static_pages#contact'
  match 'elpara', to: 'static_pages#elparasol'
  match 'telmate', to: 'static_pages#telmate'
  match 'cook', to: 'static_pages#cook'
  match 'orange', to: 'static_pages#orange'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # Rendering Views: An empty action is in fact not so empty. Remember "erb :about" in Sinatra? Rails does that for you behind the scenes. Meaning, Each and every controller action will implicitly render a view unless you tell it otherwise. By default Rails renders views as follows: views/<CONTROLLER_NAME>/<ACTION_NAME>.html.erb. You shouldn't change that behavior unless you're doing ajax work or have a really good reason. Remember: convention over configuration. Please read this: http://guides.rubyonrails.org/v3.2.13/layouts_and_rendering.html.
  # Rendering Layouts: By default, Rails will look under views/layouts/<CONTROLLER_NAME>.html.erb, if it doesn't find it, it will fall back on the parent's layout (remember, every controller inherits from application controller). Therefore, the general use case, an application will have one layout, that is the views/layouts/application.html.erb unless you decide to change it for a specific controller or action. When would you want a different layout? What if you have an Admin dashboard in your app and you don't want it to look the same as your user-facing app. Read this: http://guides.rubyonrails.org/v3.2.13/layouts_and_rendering.html
  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def privacy
  end

  def about
  end

  def contact
  end

  def blog
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Namratafolio</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/namrataproject.html.erb
<body>
	<%= render 'shared/header' %>
	<article class="article">
	 <!-- el parasol.html -->
		<h1><u>Hourly Stocks</u></h1>
			<time><span class='month'>Dec</span><span class='year'> 2015 - present</span></time>
			<p>Building website using a suite of cutting-edge predictive algorithms to perform real-time analysis of stock movement to predict the direction  of more than 7000 publicly traded stocks and ETFs on the NYSE and NASDAQ. The website allows users to trade and also keeps track of the user's gain and performance that they can see visually via graphs.<br><br><strong> Technology stack:</strong> Ruby on rails, Javscript, Jquery, AWS, Stripe, D3 and a whole bunch of cool stuff</p>

	</article>

	<article class="article">
	<!-- cr.html -->
		<h1><u>Telmate</u></h1>
			<time><span class='month'>Aug</span><span class='year'> 2014 - present</span></time>
			<p>As a full stack engineer at Telmate, I have had opportunities to work on a variety of projects and have built several projects from grounds up including Command center, which is a single framework powering all browser-based administratiin interfaces across the Telmate Ecosystem. Development tools such as robust access control system(permissions), access to ElasticSearch for real-time search, with a vast suite of hooks and registries to help build any arm of the product.<br> Built internal tools in Android to create a health check app that will monitor the health of all the dependent services that the devices communicate with, during the entire life cycle and notifies devs and QA when a certain service is unavailable.<br><br><strong>Technology stack:</strong> Ruby on rails, ReactJS, Backbone, Javscript libraries like moment, lodash, Elastic Search and native Android</p>

	</article>

	<article class="article">
	  
		<h1><u>New Mexico Corrections Department</u></h1>
			<time><span class='month'>Nov</span><span class='year'> 2013 - Feb 2014</span></time>
			<p>As an application developer at New Mexico correction's department, my responsibilities included performing application development and aiding systems analysis, design, development/enhancement of web based applications. I was also involved in migrating the legacy .Net code to Java.<br><br><strong>Technology stack:</strong> Java, .Net, Jquery, HTML, CSS</p>

	</article>

	<article class="article">
	  
		<h1><u>Cerner Health Care</u></h1>
			<time><span class='month'>Sep</span><span class='year'> 2012 - Jan 2013</span></time>
			<p>Cerner Millennium is a Hospital Management System that enables physicians, nurses and other users to share data and streamline processes across a hospital. My role included Operating System installation, hardware upgrades, periodic maintenance, and ensuring application availability for all the healthcare and hospital system clients hosted on Cerner’s Server Farms. Clients I supported include: University of New Mexico Health Sciences Center, Kansas Medical Center, University of Missouri Health Care.<br><br><strong>Technology stack:</strong> Unix, Linux, AIX, Oracle
	</article>

	<article class="article">
	  
		<h1><u>Quinnox Consulting Services</u></h1>
			<time><span class='month'>Sep</span><span class='year'> 2008 - Mar 2012</span></time>
			<p>As a programmer analyst, I worked on an information portal called Insight that can access Coca-Cola’s Financial data including Accounts Payables, Accounts Receivables, Vendor and Order Management data. The Application provides users with a simple browser-based interface for querying and reporting on financial data. It is a Java based application running on SQL Databases installed on Unix Servers.<br><br><strong>Technology stack:</strong> Unix, HTML, CSS, Java, Apache
	</article>

	<%= render 'shared/aside' %>

	<%= render 'shared/footer' %>
</body>

app/views/shared/_aside.html.erb
<aside class="sidebar">  
  <section>
    <h1 class="post_title">Technology</h1>
      <ul id="recent_posts" class="transbox" >
          
      	<li class="post">
      	  <a href="/blog">Javascript: Roll A Die, Object Oriented</a>
      	</li>

        <li class="post">
          <a href="/blog">Jquery is not magic</a>
        </li>

        <li class="post">
          <a href="/blog">Using Bcrypt for strong password encryption</a>
        </li>

        <li class="post">
          <a href="/blog">Sorting algorithms</a>
        </li>
      </ul>
  </section>

  <section>
    <h1 class="post_title">Side Projects</h1>
      <ul id="recent_posts" class="transbox">
          
        <li class="post">
          <%= link_to 'Epic Swap', elpara_path %>
        </li>

        <li class="post">
          <%= link_to 'Team NATL, a survey website', telmate_path %>
        </li>

        <li class="post">
          <%= link_to 'Jpeg Journey', cook_path %>
        </li>

        <li class="post">
          <%= link_to 'Orange Tree', orange_path %>
        </li>
      </ul>
  </section>
</aside>

app/views/shared/_footer.html.erb
<!-- <div>
	<footer class="pencil">
	  <p>Copyright © 2016 <a href="#">Namrata Honnavar</a>. All rights reserved.</p>
	</footer>
</div> -->

<div id="footer">
	<p>Copyright © 2016 Namrata Honnavar. All rights reserved.</p>
</div>

app/views/shared/_header.html.erb
<nav>
	<ul class="main-navigation">
	  <strong><li><a href="/">Employment Profile</a></li>
	  <li><%= link_to 'Blogs', blog_path %></li>
	  <li><%= link_to 'About', about_path %></li>
	</ul>
</nav>

app/views/static_pages/about.html.erb
<head>
  <title>Namrata Honnavar</title>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <link href="polaroids/polaroid.css" rel="stylesheet">
</head>

<body>
  <%= render 'shared/header' %>
  <div id="wrap">
    <div id="container">
      <h1 id="headh1">A Visual Introduction to Namrata Honnavar</h1>
        <ul class="polaroids">
          <li><a href="#" title="Yes, that's me!!"><img alt=
          "Namrata's pic" src=
          'polaroids/images/namrata.jpg' ></a></li>

          <li><a href="#" title="Lives in Livermore"><img alt=
          "The Golden Gate Bridge" 
          src="polaroids/images/livermore.jpg"></a></li><br>

          <li><a href="#" title="Originally from India"><img alt=
          "India" src=
          "polaroids/images/india.jpg"></a></li>

          <li><a href="#" title="Loves Food"><img alt=
          "Food is ultimate pleasure" src=
          "polaroids/images/food.jpg"></a></li>

          <li><a href="#" title="Loves To Travel"><img alt=
          "World is so beautiful" src=
          "polaroids/images/travel.jpg"></a></li>

          <li><a href="#" title="Full Stack Engineer"><img alt=
          "Develop beautiful and meaningful things" src=
          "polaroids/images/computer.jpg"></a></li>
        </ul>
    </div>
  </div>
</body>
  

app/views/static_pages/cook.html.erb
<nav>
	<ul class="main-navigation">
	  <strong><li><a href="/blog">Back</a></li>
		</strong>
	</ul>
</nav>
<article class="article">
  
<h1><a href="https://github.com/fiery-skippers-2014/JpegJourneys">Jpeg Journey</a></h1>
	<time datetime="2014-04-18T20:15:00-08:00" pubdate><span class='month'>April</span> <span class='day'>20</span> <span class='year'>2014</span></time>
	<p class="transbox"><strong>Jpeg Journeys is a web application that was created for users to see what their destinations looked like. Main reason behind this project was to get my feet wet in learning API's. I ended up using Flickr API, google maps API and facebook API too. This project helped me understand Active Record better. I also learnt how to use omniauth for authentication. Before using omniauth, I used Bcrypt to encrypt user's password for security. And now with Omniauth I dont't have to worry about user's authentication.<br><br>Technology Stack: Sinatra, Javscript, Jquery, HTML, CSS and API's.</strong></p>

</article>

app/views/static_pages/elparasol.html.erb
<nav>
	<ul class="main-navigation">
	  <strong><li><a href="/blog">Back</a></li>
		</strong>
	</ul>
</nav>
<article class="article">
  
	<h1><a href="https://github.com/namratahonnavar/EPICSWAP">EPIC SWAP</a></h1>
		<time datetime="2014-06-07T08:36:00-08:00" pubdate><span class='month'>May</span> <span class='day'>08</span> <span class='year'>2014</span></time>
		<p class="transbox"><strong>Epic Swap is a website designed to bring together like-minded people who love the idea of sharing knowledge and skills.This app is designed to get you off the computer and in front of another person. It takes advantage of a talented population and peoples desire to learn and teach. In addition, it is easy for people to bond over the shared acquisition of knowledge. It was mainly built with the idea of sharing skills, knowledge, and community-building for a happier community<br><br> Technology stack: Ruby on rails, Javscript, Jquery, Handlebar, HTML, CSS, saas, GooglemapsAPI, Omniauth for facebook and linkedIn</strong></p>
</article>

app/views/static_pages/orange.erb
<nav>
	<ul class="main-navigation">
	  <strong><li><a href="/blog">Back</a></li>
		</strong>
	</ul>
</nav>
<article class="article">
  
<h1><a href="https://github.com/namratahonnavar/Orange-Tree">Orange Tree</a></h1>
	<time datetime="2014-04-12T20:15:00-08:00" pubdate><span class='month'>April</span> <span class='day'>12</span> <span class='year'>2014</span></time>
	<p class="transbox"><strong>Orange tree is a pure javascript project that uses test driven development(TDD) JavaScript code with Jasmine. It also helped me understand functions, control structures and scope and to write object oriented javascript.<br>Main features of this project were, a tree can age, for each year the tree ages up to it's fruit bearing age, it gets taller.After a tree reaches fruit bearing age, it can grow fruit.A tree grows a random amount of oranges each year it ages (after reaching fruit bearing age).You can pick all the fruit that grows each year.A tree dies after it ages for it's max age years and can no longer bear fruit.<br><br>Technology Stack: Object Oriented Javscript, Jquery, Jasmine for testing javascript.

</article>

app/views/static_pages/telmate.html.erb
<nav>
	<ul class="main-navigation">
	  <strong><li><a href="/blog">Back</a></li>
		</strong>
	</ul>
</nav>
<article class="article">
  
<h1><a href="http://still-taiga-4651.herokuapp.com/ ">Team NATL, a survey website</a></h1>
<time datetime="2014-05-28T22:13:00-08:00" pubdate><span class='month'>May</span> <span class='day'>28</span> <span class='year'>2014</span></time>
<p class="transbox"><strong>Team NATL is a survey website designed for people to not only create surveys but to create a personal profile page too. It allows users to upload their favourite pictures, ask questions, take survey and much more. At any point the user can edit or delete his profile too. And the cool part is users can vote for a particular survey and see high charts that show  the most voted answer.<br><br>Technology Stack: Sinatra, Javscript, Jquery, Handlebar, HTML, CSS, Highcharts. </strong></p>

</article>